# Generated by Django 3.1 on 2020-09-03 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0005_auto_20200901_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='fcm_token',
            field=models.TextField(default=''),
        ),
    ]
