# Generated by Django 3.1 on 2020-09-05 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0008_studentresult'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentresult',
            old_name='subject_assingment_marks',
            new_name='subject_assignment_marks',
        ),
    ]
